spring.application.name=exam-service

# ===============================
# Application Configuration
# ===============================

server.port=8083

# User Service URL
user.service.url=http://localhost:8081

# Notification Service URL
notification.service.url=http://localhost:8089/api/notifications/send-email


# Course Service URL
course.service.url=http://localhost:8090

# Add this line
certification.service.url=http://localhost:8084

# Analytics Service URL
analytics.service.url=http://localhost:8086
eureka.client.service-url.defaultZone=http://localhost:5050/eureka


# ===============================
# DataSource Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/exam_service_db
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# Hibernate / JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.configserverllp.csllp_learning_platform.user_service=DEBUG
