# Application Configuration
spring.application.name=certification-service
server.port=8084
eureka.client.service-url.defaultZone=http://localhost:5050/eureka

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/certification_service_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# External Services
user.service.url=http://localhost:8081
course.service.url=http://localhost:8090
exam.service.url=http://localhost:8083

# Certificate Storage
certificate.storage.path=./certificates

# CORS
spring.web.cors.allowed-origins=http://localhost:3000

# Logging
logging.level.com.configserverllp.csllp_learning_platform.certification_service=DEBUG