spring.application.name=course-service

# ===============================
# Application Configuration
# ===============================

server.port=8090

# ===============================
# DataSource Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/course_service_db
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# Hibernate / JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Notification & User Service URLs (change host/ports if your services run on different ports)
notification.service.url=http://localhost:8089/api/notifications/send-email
user.service.base-url=http://localhost:8081
material.service.base-url=http://localhost:8082


# ? AUTOMATIC REMINDER CONFIGURATION
# Enable scheduling
spring.task.scheduling.pool.size=2


# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.configserverllp.csllp_learning_platform.user_service=DEBUG
