spring.application.name=submission-service
# ===============================
# Application Configuration
# ===============================

server.port=8084

# ===============================
# DataSource Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/submission_service_db
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# Hibernate / JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.configserverllp.csllp_learning_platform.user_service=DEBUG
